import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'

var name = ""

function postMessages() {

  const message_text = document.querySelector<HTMLTextAreaElement>('#message_text')!.value;

  if(message_text == "") {
    console.log("돌아가!");
    return;
  }

  const reqBody = {
    msgtext: message_text,
    publisher: '이름'
  }

  fetch('http://localhost:3000/api/db', {
    method: 'POST',
    body: JSON.stringify(reqBody),
    headers: {
      'Content-Type' : 'application/json',
    },
  })
  .then(res => res.json)
  .then(data => console.log(data));
  
  document.querySelector<HTMLTextAreaElement>('#message_text')!.value = "";
  
  location.reload();
}

function getRandomColor() {
  var rand = Math.floor(Math.random()*7);
  if(rand == 0) return styles.red;
  else if(rand==1) return styles.orange;
  else if(rand==2) return styles.yellow;
  else if(rand==3) return styles.green;
  else if(rand==4) return styles.cyan;
  else if(rand==5) return styles.blue;
  else if(rand==6) return styles.magenta;
}

function nameSet() {
  document.getElementById('nameSetDiv')?.classList.add('active');
}

export async function getStaticProps() {

  const res = await fetch('http://localhost:3000/api/db')
  const result = await res.json()

  if(!result) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      }
    }
  }

  return {
    props: {
      result,
    },

    revalidate: 10,
  }
}

interface msg {msgid: number, msgtext: string, publisher: string, timedate: string};

function Home( result: msg[] ) {

  console.log(result);  
  var msgList:msg[] = [];

  var idx = 1;
  result.forEach(function (value: any) {
    const nextMsg: msg = {
      msgid: idx,
      msgtext: value.msgtext,
      publisher : value.publisher,
      timedate : value.timedate,
    }
    msgList.push(nextMsg);

    idx++;
  })

  const msgView = msgList.map(msg =>
    <div key={msg.msgid}>
      <Image src={'/'+(Math.floor(Math.random()*9)+1)+'.png'} className={styles.heart}></Image>
      <div>
        <div>
          <h2>{msg.publisher}</h2>
          <a>{msg.timedate.substr(0, 5)}</a>
        </div>
        <a>{msg.msgtext}</a>
      </div>
    </div>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>방명록💌</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chaeeee.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.chat}>
          <a></a>
          {msgView}
        </div>
        <div className={styles.top_bar}>
          <Link href = "/">
            <Image src="/left-arrow.png"></Image>
          </Link>
          <Image src="/chaeeee.png"></Image>
          <p>채연아 태어나줘서 고마워~</p>
        </div>
        <div className={styles.bottom_bar}>
          <div id="nameSetDiv" className={styles.nameSetDiv}>
            <textarea placeholder='이름 입력..' id='name_textarea'></textarea>
          </div>
          <Image src='/setting.png' className={styles.setting} onClick={nameSet}></Image>
          <div>
            <textarea placeholder='메시지 입력..' className={styles.textArea} id='message_text'></textarea>
            <Image src="/send.png" onClick={postMessages}></Image>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
