import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

function test() {
  var message_text = document.getElementById('message_text');
  fetch('/api/messages', {
    method: 'POST',
    headers: {'content-type' : 'application/json'},
    body:JSON.stringify({
      username:'fetch', text:message_text.value
    })
  })
  .then(
    function(response) {
      console.log('status', response.status);
      return response.json()
    }
  )
  .then(
    function(result) {
      console.log(result)
    }
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>방명록💌</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chaeeee.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top_bar}>
          
        </div>
        <h1>hello world</h1>
        <div className={styles.bottom_bar}>
          <img src='/setting.png' className={styles.setting}></img>
          <div>
            <textarea placeholder='메시지 입력..' className={styles.textArea} id='message_text'></textarea>
            <img src="/send.png" onClick={test}></img>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
