import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>🎈🎉채연이🍰🎁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chaeeee.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.guestbook}>
          <a className={styles.h1}>이채연님<br/>생신이시다.<br/>한 말씀 올려드리자.</a>

          <div className={styles.like_cnt}>
            <img src='heart.png'></img>
            <h2>2843</h2>
          </div>
          
          <div className={styles.button}>
            <Link href="/guest" className={styles.goto}>
              <div className={styles.goto}>
                  <h1>방명록 작성하러 가기</h1>
              </div>
            </Link>
            <a></a>
            <div className={styles.like}>
              <img src='heart.png'></img>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
